services:
  migrate:
    build: .
    env_file:
      - .env
    command: ["./migrate"]

  app:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8099:8099"
    env_file:
      - .env
    restart: unless-stopped